### PR TITLE
Fix completions in debugger's receiver inspector

### PR DESCRIPTION
**Pull request by LinqLover**
Since Squeak 6.0, both inspectors in the debugger have the same do-it context, meaning that you can also access the temporary variables from the receiver inspector on the left. To honor this in Autocompletion, move up the logic from `#completionAdditionals` and `#guessTypeForName:` from `ContextVariablesInspector` to `Inspector`.

## Questions to be solved

- ~~Does Autocompletion intend to provide accurate support for Squeak 5.3? If yes, please ping me and I will add a version switch.~~ (does not apply to this change)

  - As I already asked this question twice, it might be helpful to add a short note about the exact compatibility requirements to the readme. :-)

## Before/after illustrations

<table>
<thead>
<tr>
<td></td>
<td>Type guessing</td>
<td>Completion additionals</td>
</tr>
</thead>
<tbody>
<tr>
<td>Before</td>
<td></td>
<td></td>
</tr>
<tr>
<td>After</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>

### CODE REVIEW

**Comment by LeonMatthes** [comment]
Change looks good overall.
I currently prefer keeping support for Squeak 5.3 if possible.
So some sort of version check is needed.

Also, adding tests to the Autocompletion is something that needs to happen at some point, to ensure support for different versions stays in place.

**Comment by LinqLover** [comment]
Thank you for your review! After rechecking, I noticed that you actually cannot use `ThisContext` in the debugger's receiver inspector in 5.3. So in this particular case, I was wrong about the need for a version switch and the feature already works correctly in Squeak 5.3. Anything else to do before this can be merged? :)

**Comment by LinqLover** [comment]
@LeonMatthes Can we merge this? :)

**Review by LeonMatthes — APPROVED** [review]
Hi, sorry this took so long :see_no_evil: 
I'll just assume this works in Squeak 5.3, like you reported.

**Pull request merged**
