### PR TITLE
Proposal: Automatically disable autocompletion for models that reject Shout styling

### PR DESCRIPTION
**Pull request by LinqLover**
## Reasoning

Both Autocompletion and Shout follow two relatively similar goals, i.e., to enhance the editing support in arbitrary tools that display source code. By using a simple heuristic that adopts the decision of a tool whether its contents should be syntax-highlighted, we can reduce the adaptation effort of tools for Autocompletion. Since Shout is already a part of the base system, a vast majority of tools can be assumed to implement proper information for syntax highlighting.

## Implementation

In `StringHolder >> #wantsAutocompletion`, redirect to `#aboutToStyle:requestor:` and pass a pseudo-styler (`MessageCatcher`) and a `nil` requestor. For the unlikely event that anything breaks (because some tool might expect a non-nil requestor or a certain styler type), catch any errors, log them to the transcript, and reject autocompletion.

## Considerations

- [x] `#aboutToStyle:requestor:` (with the second argument) is a relatively new selector that is only included in Squeak 5.3 and newer. If Autocompletion intends to provide further backward compatibility, a version switch could be introduced.

  **What backward compatibility should be supported?**

- [x] For the pseudo-styler, a more reliable alternative to using a generic `MessageCatcher` could be instantiating a real `SHStylerST80`. However, this would add a hard dependency on Shout whereas, at the moment, we only rely on the existence of the `#aboutToStyle:requestor:` protocol which is part of the Kernel package.

  **Is it okay to stick with the current `MessageCatcher` approach?**

### Workspace

<p float="middle">

</p>

### Browser

<p float="middle">

</p>

### CODE REVIEW

**Comment by LinqLover** [comment]
By the way: Maybe Autocompletion should also support a protocol `wantsAutocompletionForRequestor:` analogously to `Model>>#aboutToStyle:requestor:`?

**Comment by LeonMatthes** [comment]
Regarding support:
Squeak 5.3 and newer is fine.

As you said, using SHStylerST80 would introduce a hard dependency on Shout.
Therefore I suggest the following:
If the class `SHStylerST80` exists (check with `Smalltalk at:`), use it with `#aboutToStyle:requestor:`.
Otherwise, simply `^ true.` from `#wantsAutocompletion`, as we did before.
That way, we're not using the MessageCatcher in aboutToStyle, which could introduce strange behavior depending on what implementors of `#aboutToStyle:requestor:` expect.
And we're also not adding a hard dependency on the existence of Shout, we're just taking advantage of it, if it exists.

**Comment by LinqLover** [comment]
Thank you! Done, please recheck :)

**Review by LeonMatthes — APPROVED** [review]
LGTM

**Pull request merged**
